{
 "title": "Prom-Exporter Instance Dashboard v2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(ClickHouse_ServiceInfo,clickhouse_service_name)"
    }
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": {
     "query": "label_values(ClickHouse_ServiceInfo{clickhouse_service_name=\"$service_name\"},clickhouse_service)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of records",
   "type": "stat",
   "description": "Number of databases per service. Includes system databases.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "records" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "current_data_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Drifted Clolumns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "drift_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Columns",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Columns" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "columns_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Accuracy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "accuracy*100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recall",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "recall * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Precision",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "precision * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "f1_score",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "f1_score * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Percentage of Drifted Columns",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drift_share * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Payment Method Electronic Check Drift",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "payment_method_Electronic_check_drift * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internet Service Fiber Optic Fibre Drift",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "internet_service_Fiber_optic_drift * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monthly Charges Drift",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monthly_charges_drift * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Paperless Billing Drift",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "paperless_billing_drift * 100", "legendFormat": "__auto" }
   ]
  },
  { "title": "Queries Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } }
 ]
}